### ISSUE TITLE
Obsidian Vault Name in the URL added to the Things does percent encode spaces

### ISSUE THREAD

**Issue by Crambeary** [royxue/obsidian-things3-sync#10]
My Obsidian Vault name is "My Obsidian Vault", the url I see in the Things task note shows `obsidian://open?vault=My Obsidian Vault` - This causes anything after `My` to become text instead of a hyperlink. This is fixed with percent encoding the vault name, just like the file name which does work as expected.

**Comment by royxue** [comment]
@Crambeary 
Yes, you are right, thanks for submit this issue, I will fix this bug in the next release

**Comment by Crambeary** [comment]
@royxue Thanks for getting to it  so fast! This plugin is great so far, thank you for your work

**Comment by royxue** [comment]
@Crambeary 
I just noticed this bug was already fixed in v1.2.1, could you please update the version and retry?

**Comment by Crambeary** [comment]
@royxue 
I reinstalled it again but I still have the same problem. The version is 1.2.1, so that’s odd…
My current attempt was on mobile if that makes a difference

**Comment by royxue** [comment]
@Crambeary 
thats odd, but i just released a new 1.2.2
could you try this, hope it can help you

**Comment by Crambeary** [comment]
@royxue 
Thank you for the release! I see where you added the URL Encoding, that should do it for good. I can confirm that works fine on iOS mobile and Desktop. I'd say this can be closed
